spring.application.name=InventoryService
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:3306/retail
spring.datasource.username=mili
spring.datasource.password=mili1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
